config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :near_asteroids, only: [:index, :show]
  resources :tech_transfer, only: [:index]
  resources :astronomy, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/astronomy_controller.rb
class AstronomyController < ApplicationController
  def index
    client = NasaApi::Client.new
    @astronomy = client.astronomy_picture
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/near_asteroids_controller.rb
class NearAsteroidsController < ApplicationController
  rescue_from 'NasaApi::Client::AsteroidIdNotFound', with: :asteroid_id_not_found

  def index
    client = NasaApi::Client.new
    @neo_browse = client.neo_browse
  end

  def show
    client = NasaApi::Client.new
    @asteroid_info = client.neo_search(params[:id])
  end

  private

  def asteroid_id_not_found
    render plain: 'asteroid id not found'
  end
end

app/controllers/tech_transfer_controller.rb
class TechTransferController < ApplicationController
  def index
    client = NasaApi::Client.new
    @tech_transfer = client.tech_transfer
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/astronomy_helper.rb
module AstronomyHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/near_asteroids_helper.rb
module NearAsteroidsHelper
end

app/helpers/tech_transfer_helper.rb
module TechTransferHelper
end

app/views/astronomy/index.html.erb
<div class="container content">
    <div class="columns">
        <div class="column">
            <h1> Astronomy Random Picture by NASA api </h1>
        </div>
    </div>
    <div class="columns">
        <div class="column">
            <img src=<%= @astronomy[0]['hdurl'] %> alt="astronomy picture">
        </div>
    </div>

    <div class="columns">
        <div class="column">
            <h5>Caption:</h5>
            <p><%= @astronomy[0]['explanation'] %></p>
        
             <%= button_to 'back', root_path, class: 'button is-primary', method: :get %>
        </div>
    </div>
</div>

app/views/home/index.html.erb
<div class="container mt-3 content has-text-centered">
    <div class="columns">
        <div class="column">
            <%= image_tag 'nasa-logo-web-rgb.png', class: 'is-rounded'%>
        </div>
    </div>

    <div class="columns has-text-justified mb-4 ">
        <div class="column is-flex is-align-items-center is-flex-direction-column">
            <h1>Try out NASA API Now!!!</h1>
            <ul>
                <li><%= link_to '[API] NEO', near_asteroids_path%></li>
                <li><%= link_to '[API] Tech Transfer', tech_transfer_index_path %></li>
                <li><%= link_to '[API] Astronomy', astronomy_index_path  %></li>
            </ul>
        </div>
        
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApiWrapper</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('nasa_icon.ico') %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/near_asteroids/index.html.erb
<div class="container content">
    <div class="columns">
        <div class="column">
            <h1>NearAsteroids</h1>
            <% @neo_browse['near_earth_objects'].each do |asteroid_name| %>
                <ul>
                    <li>
                        <%=link_to asteroid_name['name'], near_asteroid_path(asteroid_name['neo_reference_id']) %>
                    </li>
                </ul>
            <% end %>
            <%= button_to 'back', root_path, class: 'button is-primary', method: :get %>
        </div>
    </div>
</div>

app/views/near_asteroids/show.html.erb
<div class="container content">
    <div class="columns">
        <div class="column">
            <h1><%= @asteroid_info['name'] %></h1>
            <h4>Close Approach Date</h4>
                <% @asteroid_info['close_approach_data'].each do |approach_date| %>
                    <ul>
                        <li>
                            <%= approach_date['close_approach_date_full'] %>
                        </li>
                    </ul>
                <% end %>

            <%= button_to 'back', near_asteroids_path, class: 'button is-primary', method: :get %>
        </div>
    </div>
</div>

app/views/tech_transfer/index.html.erb
<div class="container content">
    <div class="columns">
        <div class="column">
            <h1>Tech Transfer</h1>
            <%= button_to 'back', root_path, class: 'button is-primary', method: :get %>
        </div>
    </div>
    <div class="columns is-multiline">
           <% @tech_transfer['results'].each do |tech| %>
                <div class="column is-4">
                    <img src="<%= tech[-3] %>" alt="tech transfer">
                </div>
        <% end %>
    </div>
</div>